// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/client_service/client_messages.proto

package chord

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileMetadata struct {
	FilenameAtOwner      string   `protobuf:"bytes,1,opt,name=filenameAtOwner,proto3" json:"filenameAtOwner,omitempty"`
	OwnersID             string   `protobuf:"bytes,2,opt,name=ownersID,proto3" json:"ownersID,omitempty"`
	NameToStore          string   `protobuf:"bytes,3,opt,name=nameToStore,proto3" json:"nameToStore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMetadata) Reset()         { *m = FileMetadata{} }
func (m *FileMetadata) String() string { return proto.CompactTextString(m) }
func (*FileMetadata) ProtoMessage()    {}
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea5e10a184d1a4d, []int{0}
}

func (m *FileMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadata.Unmarshal(m, b)
}
func (m *FileMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadata.Marshal(b, m, deterministic)
}
func (m *FileMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadata.Merge(m, src)
}
func (m *FileMetadata) XXX_Size() int {
	return xxx_messageInfo_FileMetadata.Size(m)
}
func (m *FileMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadata proto.InternalMessageInfo

func (m *FileMetadata) GetFilenameAtOwner() string {
	if m != nil {
		return m.FilenameAtOwner
	}
	return ""
}

func (m *FileMetadata) GetOwnersID() string {
	if m != nil {
		return m.OwnersID
	}
	return ""
}

func (m *FileMetadata) GetNameToStore() string {
	if m != nil {
		return m.NameToStore
	}
	return ""
}

type Response struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea5e10a184d1a4d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*FileMetadata)(nil), "chord.FileMetadata")
	proto.RegisterType((*Response)(nil), "chord.Response")
}

func init() {
	proto.RegisterFile("services/client_service/client_messages.proto", fileDescriptor_5ea5e10a184d1a4d)
}

var fileDescriptor_5ea5e10a184d1a4d = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x89, 0x87, 0xf2, 0x61, 0xdc,
	0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0xd4, 0x62, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xd6,
	0xe4, 0x8c, 0xfc, 0xa2, 0x14, 0xa5, 0x32, 0x2e, 0x1e, 0xb7, 0xcc, 0x9c, 0x54, 0xdf, 0xd4, 0x92,
	0xc4, 0x94, 0xc4, 0x92, 0x44, 0x21, 0x0d, 0x2e, 0xfe, 0xb4, 0xcc, 0x9c, 0xd4, 0xbc, 0xc4, 0xdc,
	0x54, 0xc7, 0x12, 0xff, 0xf2, 0xbc, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x74,
	0x61, 0x21, 0x29, 0x2e, 0x8e, 0x7c, 0x10, 0xa3, 0xd8, 0xd3, 0x45, 0x82, 0x09, 0xac, 0x04, 0xce,
	0x17, 0x52, 0xe0, 0xe2, 0x06, 0x29, 0x0d, 0xc9, 0x0f, 0x2e, 0xc9, 0x2f, 0x4a, 0x95, 0x60, 0x06,
	0x4b, 0x23, 0x0b, 0x29, 0xc9, 0x71, 0x71, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a,
	0x09, 0x71, 0xb1, 0x94, 0xa4, 0x56, 0x94, 0x40, 0x2d, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xae, 0x34,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x16, 0x59, 0xf8, 0x66, 0xd6, 0x00, 0x00, 0x00,
}
